# Tables from Scanned Pages

```r
library(Rtesseract)
```

```r
file = "1990_p44.png"

```

We discard the rows below and including MEAN and also at and above ENTRY.
```r
  i = which(rownames(bb) == "MEAN")
  if(length(i))
      bb = bb[ bb[, "top"] <  bb[i, "top"], ]

  if(length(i <- grep("ENTRY", rownames(bb), ignore.case = TRUE) ))
     bb = bb[ bb[, "top"] > bb[i , "top"] + 10  , ]
```

We also remove the elements related to the ranking of the values, i.e. with a ( or ) or a { or }
since tesseract sometimes confuses ( and ) with { and }:
```
           # Get rid of the rank values
  i = grepl("^[({]$|^\\(?[0-9]+[\\)}]$", rownames(bb))
  bb = bb[!i, ]
```


Now that we have the line information, we do more.

Interestingly, in 1990-p45.png, tesseract gives us all but one of the lines.
It does not detect the one under FORAGE YIELD, but it does  find the two
lines under TULARE and KINGS, but considers it one entire line.


There are still entries with ) because the digits were incorrectly recognized as letters, e.g. "A)"
```
  i = grepl("\\)$", rownames(bb))
  bb = bb[!i, ]
```


So we have the body of the table.
Find the

 We know the number of lines in the body - 18. What does this give us.
```r
ll = cut(bb[, "bottom"], 18)
split(rownames(bb),  ll)
```

If we know the number of lines, we get a good split of the elements into lines.
So how can we determine the number of lines programmatically.

If we knew the number of columns, we could use equal.count(), but in the scanned doc, there are often more elements
within each cell (row-column combination).


We can group by the value of bb[, "bottom"]
```r
tt = table(bb[, "bottom"])
```
> 849  891  933  974  975  976 1016 1017 1057 1058 1100 1139 1140 1141 1142 1183 1184 1224 1226 1227 1269 1270 1309 1311 1353 1393 1395 1437 1477 1478 1519 1561 
>   5    5    6    2    2    1    4    1    1    4    5    1    1    3    2    2    3    1    3    2    4    1    1    5    4    1    5    6    1    4    5    5 

Now we can find the most common number of entries in each of these "lines"
```
table(tt)
```
> 1  2  3  4  5  6 
> 10  5  3  5  7  2 

So there are 10 values of bottom with just one entry.
We can see this in the value of `tt` where we have 975 with one entry and then 976

So let's look at the differences in the values of these "bottom" values:
```
lb = diff(as.integer(names(tt)))
```
> [1] 42 42 41  1  1 40  1 40  1 42 39  1  1  1 41  1 40  2  1 42  1 39  2 42 40  2 42 40  1 41 42

It is reasonably clear that the values 1 and 2 are on the same line.
This is because the "majority" of these values are around 39 - 42.
However, this is not true
```
table(lb)
```
>lb
> 1  2 39 40 41 42 
>11  3  2  5  3  7 

So the most common value is 1, the next is 2.
Then we get to real differences.
So we have to use contextual knowledge.
So let's group the values of bottom that are different by less than 1/5 of the maximum value.
```
u = unique(bb[, "top"])
i = abs(diff(u)) >  13 # 8
lineBreaks = nrow(img) - u[i] 
```

```
abline(h = nrow(img)  - lineBreaks, col = "blue")
```


```
byline = split(rownames(bb), cut(bb[, "bottom"], c(lineBreaks - 4, Inf)))
```

```
unname(sapply(byline, length))
```

Let's look at the "lines" that don't have 5 elements
```
byline[ sapply(byline, length) != 5 ]
```
```
$`(0,847]`
character(0)

$`(931,972]`
[1] "4"    "CAL"  "RED"  "1560" "1490" "1570"

$`(1.14e+03,1.18e+03]`
[1] "95"            "750—036-83-10" "4370"          "4100"          "4130"          "f"            

$`(1.35e+03,1.39e+03]`
[1] "104"      "A81-0006" "2620"     "2190"    

$`(1.39e+03,1.44e+03]`
[1] "106"     "BZSH163" "3290"    "2620"    "i"       "2750"   

$`(1.44e+03,1.48e+03]`
[1] "107"   "COKER" "81072" "2850"  "2590"  "2760" 
```


For the lines that have 5 columns, let's find their positions.
```
bb = bboxToDF(bb)
breaks = cut(bb[, "bottom"], c(lineBreaks - 2, Inf))
bb.lines = split(bb, breaks)
```

For the regular PDF  documents, we can use getOkColPositions.
However, this doesn't work for these documents
```
pos = getOkColPositions(bb.lines[  sapply(bb.lines, nrow) == 5 ])
abline(v = pos, col = "green", lwd = 3)
```
The problem is that some of the lines that have 5 elements are not correct.
For example, the last of these lines has the elements
111, OT, 03669, 2270, 1920. The second and third of these need to be combined
into a single column. The value for the fifth column is missing. Accordingly, the positions
misrepresent the actual columns.

So rather than taking the minimum of each of the left positions of the columns,
we have to use the majority, defined in some way.

tmp= bb.lines[  sapply(bb.lines, nrow) == 5 ]
tmp = lapply(tmp, function(x) as.numeric(t(getColPositions(x))))
colPos = do.call(rbind, tmp)
